import base64
import json

from nose.tools import istest
from svc import constants
from svc import lambda_function

FIXTURE = {'workflow_activity': {'activity_name': 'Flowcell Setup',
                                 'activity_type': 'pool-samples',
                                 'configuration': {'destinationContainers': [{'containerTypes': ['1 Lane Flow Cell',
                                                                                                 '2 Lane Flow Cell'],
                                                                              'destinationMetadata': [
                                                                                  {'key': 'concentration',
                                                                                   'name': 'Concentration '
                                                                                           '(ng/µl)',
                                                                                   'renderType': 'text'}],
                                                                              'label': 'Flowcell',
                                                                              'sampleLabel': 'pooled-barcoded-dna',
                                                                              'sourceMetadata': ['concentration']}],
                                                   'postActivityFunctions': [{'name': 'ncgl_generateSampleSheetV1',
                                                                              'requiredToComplete': True,
                                                                              'type': 'lambda'}],
                                                   'resources': [{'label': 'sample-sheet',
                                                                  'name': 'Sample '
                                                                          'Sheet'}],
                                                   'sourceSampleStateLabel': ['pooled-barcoded-dna',
                                                                              'pooled-captured-barcoded-dna']},
                                 'custom_attributes': {'flowCellId': '',
                                                       'index1': '',
                                                       'index2': '',
                                                       'read1': '',
                                                       'read2': '',
                                                       'singleRead': True},
                                 'id': 5565,
                                 'resources': [],
                                 'status': 'processing',
                                 'workflow': {'id': 680,
                                              'samples': [{'control': False,
                                                           'custom_attributes': {},
                                                           'date_received': '2018-08-16',
                                                           'id': 1939,
                                                           'identifier': 'ngs-standard-uwc1.1',
                                                           'patient': {'date_of_birth': None,
                                                                       'ethnicity': None,
                                                                       'first_name': None,
                                                                       'gender': None,
                                                                       'id': 1166,
                                                                       'identifier': 'ngs-standard-uwc1',
                                                                       'last_name': None,
                                                                       'patient_uuid': None,
                                                                       'requisition_id': 1376},
                                                           'physician': None,
                                                           'received': True,
                                                           'requisition': {'accession_status': 'signed',
                                                                           'billing_status': 'not-submitted',
                                                                           'custom_attributes': {},
                                                                           'diagnosis': None,
                                                                           'id': 1376,
                                                                           'identifier': 'ngs-standard-uwc1',
                                                                           'medications': None,
                                                                           'processing_status': 'processing',
                                                                           'project_name': 'Research '
                                                                                           'NGS',
                                                                           'requested_tests': {'pgeneric-comp': True},
                                                                           'sample_collection_date': '2018-08-12',
                                                                           'sample_type': None,
                                                                           'uuid': '927dfd7f-24a5-4fc6-a33b-163c5108c7e6'},
                                                           'requisition_id': 1376,
                                                           'sample_states': [{'container_barcode_label': 'suwc1',
                                                                              'id': 56450,
                                                                              'internal_position': 1,
                                                                              'metadata': None,
                                                                              'pool_index': '0',
                                                                              'position': 'a01',
                                                                              'sample_id': 1939,
                                                                              'source_sample_state_id': None,
                                                                              'workflow_activity_id': None},
                                                                             {'container_barcode_label': 'P000000003HE',
                                                                              'id': 56456,
                                                                              'internal_position': 1,
                                                                              'metadata': None,
                                                                              'pool_index': '0',
                                                                              'position': 'A01',
                                                                              'sample_id': 1939,
                                                                              'source_sample_state_id': 56450,
                                                                              'workflow_activity_id': 4770},
                                                                             {'container_barcode_label': 'P000000003HE',
                                                                              'id': 56462,
                                                                              'internal_position': 1,
                                                                              'metadata': None,
                                                                              'pool_index': 'ADP313-1',
                                                                              'position': 'A01',
                                                                              'sample_id': 1939,
                                                                              'source_sample_state_id': 56450,
                                                                              'workflow_activity_id': 4771},
                                                                             {'container_barcode_label': 'P000000003HG',
                                                                              'id': 56468,
                                                                              'internal_position': 1,
                                                                              'metadata': {'concentration': '3'},
                                                                              'pool_index': 'ADP313-1',
                                                                              'position': 'A01',
                                                                              'sample_id': 1939,
                                                                              'source_sample_state_id': 56462,
                                                                              'workflow_activity_id': 4775},
                                                                             {'container_barcode_label': 'P000000004A0',
                                                                              'id': 67291,
                                                                              'internal_position': 1,
                                                                              'metadata': {},
                                                                              'pool_index': 'ADP313-1',
                                                                              'position': 'A01',
                                                                              'sample_id': 1939,
                                                                              'source_sample_state_id': 56468,
                                                                              'workflow_activity_id': 5565}],
                                                           'sample_uuid': None,
                                                           'workflow_sample_results': [{'computed_status': None,
                                                                                        'id': 2050,
                                                                                        'result': {
                                                                                            'library-adapter-barcode': {
                                                                                                'records': [
                                                                                                    {
                                                                                                        'Adapter Set': 'Alpha',
                                                                                                        'I5 Sequence': 'TATAGCCT',
                                                                                                        'I7 Sequence': 'GAGATTCC',
                                                                                                        'Index 1 (I7)': 'D704',
                                                                                                        'Index 2 (I5)': 'D501',
                                                                                                        'Name': 'ADP313-1',
                                                                                                        'Project': 'General',
                                                                                                        'barcode': 'ADP313-1'}]}},
                                                                                        'result_type': 'library-adapter-barcode',
                                                                                        'routing': None,
                                                                                        'sample_id': 1939,
                                                                                        'status': None,
                                                                                        'workflow_activity_id': 4771,
                                                                                        'workflow_sample_id': 1797},
                                                                                       {'computed_status': None,
                                                                                        'id': 2056,
                                                                                        'result': {'libraryQC': {
                                                                                            'records': [{
                                                                                                'Average Fragment Size (bp)': '300',
                                                                                                'Fragmentation conditions': 'None',
                                                                                                'PCR Cycle #': '15',
                                                                                                'Qubit: Broad Range or High Sensitivity': '34.1',
                                                                                                'Spike-In Dilution Factor': '1',
                                                                                                'Spike-In Volume': '0.885888977',
                                                                                                'Total Quantity (ng)': '579.7',
                                                                                                'Volume (uL)': '17'}],
                                                                                            'status': 'unknown'}},
                                                                                        'result_type': 'library-quality-check',
                                                                                        'routing': 'accepted-genome',
                                                                                        'sample_id': 1939,
                                                                                        'status': 'accepted',
                                                                                        'workflow_activity_id': 4772,
                                                                                        'workflow_sample_id': 1797}]},
                                                          {'control': False,
                                                           'custom_attributes': {},
                                                           'date_received': '2018-08-16',
                                                           'id': 1940,
                                                           'identifier': 'ngs-standard-uwc2.1',
                                                           'patient': {'date_of_birth': None,
                                                                       'ethnicity': None,
                                                                       'first_name': None,
                                                                       'gender': None,
                                                                       'id': 1167,
                                                                       'identifier': 'ngs-standard-uwc2',
                                                                       'last_name': None,
                                                                       'patient_uuid': None,
                                                                       'requisition_id': 1377},
                                                           'physician': None,
                                                           'received': True,
                                                           'requisition': {'accession_status': 'signed',
                                                                           'billing_status': 'not-submitted',
                                                                           'custom_attributes': {},
                                                                           'diagnosis': None,
                                                                           'id': 1377,
                                                                           'identifier': 'ngs-standard-uwc2',
                                                                           'medications': None,
                                                                           'processing_status': 'processing',
                                                                           'project_name': 'Research '
                                                                                           'NGS',
                                                                           'requested_tests': {'pgeneric-comp': True},
                                                                           'sample_collection_date': '2018-08-13',
                                                                           'sample_type': None,
                                                                           'uuid': '0f044f94-729e-4559-af75-c9b74817b9b1'},
                                                           'requisition_id': 1377,
                                                           'sample_states': [{'container_barcode_label': 'suwc2',
                                                                              'id': 56451,
                                                                              'internal_position': 1,
                                                                              'metadata': None,
                                                                              'pool_index': '0',
                                                                              'position': 'a01',
                                                                              'sample_id': 1940,
                                                                              'source_sample_state_id': None,
                                                                              'workflow_activity_id': None},
                                                                             {'container_barcode_label': 'P000000003HE',
                                                                              'id': 56457,
                                                                              'internal_position': 13,
                                                                              'metadata': None,
                                                                              'pool_index': '0',
                                                                              'position': 'B01',
                                                                              'sample_id': 1940,
                                                                              'source_sample_state_id': 56451,
                                                                              'workflow_activity_id': 4770},
                                                                             {'container_barcode_label': 'P000000003HE',
                                                                              'id': 56463,
                                                                              'internal_position': 13,
                                                                              'metadata': None,
                                                                              'pool_index': 'ADP314-1',
                                                                              'position': 'B01',
                                                                              'sample_id': 1940,
                                                                              'source_sample_state_id': 56451,
                                                                              'workflow_activity_id': 4771},
                                                                             {'container_barcode_label': 'P000000003HG',
                                                                              'id': 56469,
                                                                              'internal_position': 1,
                                                                              'metadata': {'concentration': '3'},
                                                                              'pool_index': 'ADP314-1',
                                                                              'position': 'A01',
                                                                              'sample_id': 1940,
                                                                              'source_sample_state_id': 56463,
                                                                              'workflow_activity_id': 4775},
                                                                             {'container_barcode_label': 'P000000004A0',
                                                                              'id': 67292,
                                                                              'internal_position': 1,
                                                                              'metadata': {},
                                                                              'pool_index': 'ADP314-1',
                                                                              'position': 'A01',
                                                                              'sample_id': 1940,
                                                                              'source_sample_state_id': 56469,
                                                                              'workflow_activity_id': 5565}],
                                                           'sample_uuid': None,
                                                           'workflow_sample_results': [{'computed_status': None,
                                                                                        'id': 2051,
                                                                                        'result': {
                                                                                            'library-adapter-barcode': {
                                                                                                'records': [
                                                                                                    {
                                                                                                        'Adapter Set': 'Alpha',
                                                                                                        'I5 Sequence': 'ATAGAGGC',
                                                                                                        'I7 Sequence': 'ATTCAGAA',
                                                                                                        'Index 1 (I7)': 'D705',
                                                                                                        'Index 2 (I5)': 'D502',
                                                                                                        'Name': 'ADP314-1',
                                                                                                        'Project': 'General',
                                                                                                        'barcode': 'ADP314-1'}]}},
                                                                                        'result_type': 'library-adapter-barcode',
                                                                                        'routing': None,
                                                                                        'sample_id': 1940,
                                                                                        'status': None,
                                                                                        'workflow_activity_id': 4771,
                                                                                        'workflow_sample_id': 1798},
                                                                                       {'computed_status': None,
                                                                                        'id': 2057,
                                                                                        'result': {'libraryQC': {
                                                                                            'records': [{
                                                                                                'Average Fragment Size (bp)': '300',
                                                                                                'Fragmentation conditions': 'None',
                                                                                                'PCR Cycle #': '15',
                                                                                                'Qubit: Broad Range or High Sensitivity': '29.5',
                                                                                                'Spike-In Dilution Factor': '1',
                                                                                                'Spike-In Volume': '0.453135222',
                                                                                                'Total Quantity (ng)': '501.5',
                                                                                                'Volume (uL)': '17'}],
                                                                                            'status': 'unknown'}},
                                                                                        'result_type': 'library-quality-check',
                                                                                        'routing': 'accepted-genome',
                                                                                        'sample_id': 1940,
                                                                                        'status': 'accepted',
                                                                                        'workflow_activity_id': 4772,
                                                                                        'workflow_sample_id': 1798}]}],
                                              'status': 'processing',
                                              'workflow_sample_results': []}}}


@istest
def should_return_sample_sheet_csv():
    sample_sheet = '[Header],,,,,,,,,,,\r\n,,,,,,,,,,,\r\n[Reads],,,,,,,,,,,\r\n,,,,,,,,,,,\r\n[Settings],,,,,,,,,,,\r\n,,,,,,,,,,,\r\n[Data],,,,,,,,,,,\r\nSample_ID,Sample_Name,Lane,FCID,Adapter Set,I5 Sequence,I7 Sequence,Index 1 (I7),Index 2 (I5),Name,Project,barcode\r\nngs-standard-uwc1.1,ngs-standard-uwc1.1,1,P000000004A0,Alpha,TATAGCCT,GAGATTCC,D704,D501,ADP313-1,General,ADP313-1\r\nngs-standard-uwc2.1,ngs-standard-uwc2.1,1,P000000004A0,Alpha,ATAGAGGC,ATTCAGAA,D705,D502,ADP314-1,General,ADP314-1\r\n'
    encoded_sample_sheet_bytes = base64.encodebytes(sample_sheet.encode(constants.UTF8))

    response = {
        "resources": [{
            "resource_name": "sample_sheet.csv",
            "content": encoded_sample_sheet_bytes.decode(constants.UTF8),
            "label": "sample-sheet"
        }]
    }

    expected = {
        'statusCode': 200,
        'body': response
    }

    assert lambda_function.lambda_handler(FIXTURE, {}) == expected
