apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-secret
  namespace: {{ .Release.Namespace }}
  labels:
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
type: Opaque
data:
  JWT_SECRET: {{ .Values.secret.JWT_SECRET  | b64enc | quote }}
  JWT_AUDIENCE: {{ .Values.secret.JWT_AUDIENCE | b64enc | quote }}
